spring:
  application:
    name: assessment-service

  config:
    import: 'configserver:'
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI}

  # Add these properties to your application.yml or application.properties
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP-SERVERS}
    consumer:
      group-id: assessment-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: java.util.Map
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true